CLASS zth_tdc4abap DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    TYPES t_dependency_list TYPE SORTED TABLE OF tablename WITH UNIQUE KEY table_line.
ENDCLASS.


CLASS zth_tdc4abap IMPLEMENTATION.
ENDCLASS.
